{% set name = "grpc_java_plugin" %}
{% set version = "1.41.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grpc/grpc-java/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c4194117805d43414c03288bdab9c137201d21f6caf6785062eaf5256d99d4e
  patches:
    - 0001-Build-against-system-libprotobuf.patch
    
#test
build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bazel
    - bazel-toolchain
    - libprotobuf
    - sed  # [osx]
  host:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/grpc_java_plugin

about:
  home: https://github.com/grpc/grpc-java/tree/master/compiler
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: gRPC Java Codegen Plugin for Protobuf Compiler

extra:
  recipe-maintainers:
    - xhochy
