{% set version = "1.55.1" %}

package:
  name: grpc_java_plugin
  version: {{ version }}

source:
  - url: https://github.com/grpc/grpc-java/archive/refs/tags/v{{ version }}.tar.gz
    sha256: be779db38a72a0c693706c433133189538b04979eba1b728eaa21f4fd0f967d8
    patches:
      - patches/0001-Build-against-system-libprotobuf.patch
      - patches/0002-use-C-17.patch
      - patches/0003-Add-abseil-libs-for-newer-protobuf-versions.patch
  {% set bz_url = "https://github.com/bazelbuild/bazel/releases/download" %}
  {% set bz_ver = "6.5.0" %}
  - fn: bazel               # [unix]
  - fn: bazel.exe           # [win]
    url: {{ bz_url }}/{{ bz_ver }}/bazel_nojdk-{{ bz_ver }}-linux-x86_64        # [build_platform == "linux-64"]
    sha256: 218ce0aed544d29084f4d9ff98f01bc784b90fe4c79dab63fa990dc68e66eaa9    # [build_platform == "linux-64"]
    url: {{ bz_url }}/{{ bz_ver }}/bazel_nojdk-{{ bz_ver }}-darwin-x86_64       # [build_platform == "osx-64"]
    sha256: ccc67fa48a6444818a5b85e8174c89ca2630df60c1e2327714d944035a240fc9    # [build_platform == "osx-64"]
    url: {{ bz_url }}/{{ bz_ver }}/bazel_nojdk-{{ bz_ver }}-darwin-arm64        # [build_platform == "osx-arm64"]
    sha256: 37017223885da29d8c42be781e8c11b84e71a3d9355b073d43b08a5dfa99229a    # [build_platform == "osx-arm64"]
    url: {{ bz_url }}/{{ bz_ver }}/bazel-{{ bz_ver }}-windows-x86_64.exe        # [build_platform == "win-64"]
    sha256: 6eae8e7f28e1b68b833503d1a58caf139c11e52de19df0d787d974653a0ea4c6    # [build_platform == "win-64"]

build:
  number: 9
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk
    - openjdk 17  # [linux]
    - bazel-toolchain
    - libprotobuf
    - sed  # [osx]
  host:
    - libabseil
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/grpc_java_plugin

about:
  home: https://github.com/grpc/grpc-java/tree/master/compiler
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: gRPC Java Codegen Plugin for Protobuf Compiler

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/bazel
    - conda-forge/grpc-cpp
