{% set version = "1.73.0" %}

{% set bz_version = "4.2.1" %}
{% set bz_base_url = "https://github.com/bazelbuild/bazel/releases/download" %}

package:
  name: grpc_java_plugin
  version: {{ version }}

source:
  - url: https://github.com/grpc/grpc-java/archive/refs/tags/v{{ version }}.tar.gz
    sha256: eca44a9f3eb341daf7a01482b96016dfa7d91baee495a697746c4724868a06db
    patches:
      - patches/0001-Build-against-system-libprotobuf.patch
      - patches/0002-use-C-17.patch
      - patches/0003-Add-abseil-libs-for-newer-protobuf-versions.patch

  - fn: bazel
    url: {{ bz_base_url }}/{{ bz_version }}/bazel_nojdk-{{ bz_version }}-linux-x86_64   # [build_platform == "linux-64"]
    sha256: cbccf5c02d404b4d3fdcc347e8cf1fc9a40e232905a1a8745499a82bdfaf00af            # [build_platform == "linux-64"]
    url: {{ bz_base_url }}/{{ bz_version }}/bazel_nojdk-{{ bz_version }}-darwin-x86_64  # [build_platform == "osx-64"]
    sha256: df204b5fdd93571eeb9aea48b8d2328ae39ed0f27f137c5c0d9281d6145d2f21            # [build_platform == "osx-64"]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk
    - openjdk 21  # [linux]
    - bazel-toolchain
    - libprotobuf
    - sed  # [osx]
  host:
    - libabseil
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/bin/grpc_java_plugin

about:
  home: https://github.com/grpc/grpc-java/tree/master/compiler
  license: Apache-2.0
  license_family: MIT
  license_file: LICENSE
  summary: gRPC Java Codegen Plugin for Protobuf Compiler

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/bazel
    - conda-forge/grpc-cpp
