bot:
  abi_migration_branches:
  - 1.37.x
  - 1.46.x
  automerge: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
test_on_native_only: true
