build_platform: {osx_arm64: osx_64, linux_aarch64: linux_64, linux_ppc64le: linux_64}
conda_forge_output_validation: true
bot:
  automerge: true
os_version:
  linux_64: cos7
conda_build:
  pkg_format: '2'
test: native_and_emulated
